In [2]:
import tensorflow as tf

y_true = [[0,1,0],[0,0,1]]
y_pred = [[0.05,0.95,0],[0.1,0.8,0.1]]
loss = tf.keras.losses.categorical_crossentropy(y_true,y_pred)
loss.numpy()

array([0.05129331, 2.3025851 ], dtype=float32)

In [3]:
import tensorflow as tf

y_true = [[1],[2]]
y_true = tf.one_hot(y_true, depth=3)
print(y_true)
y_true = tf.reshape(y_true, [-1,3])
print(y_true)
y_pred = [[0.05,0.95,0],[0.1,0.8,0.1]]

loss = loss = tf.keras.losses.categorical_crossentropy(y_true,y_pred)
loss.numpy()

tf.Tensor(
[[[0. 1. 0.]]

 [[0. 0. 1.]]], shape=(2, 1, 3), dtype=float32)
tf.Tensor(
[[0. 1. 0.]
 [0. 0. 1.]], shape=(2, 3), dtype=float32)


array([0.05129331, 2.3025851 ], dtype=float32)

In [4]:
import tensorflow as tf
import numpy as np

y_true = tf.reshape(tf.one_hot([[1],[2]], depth=3),[-1,3])
y_pred = [[0.05,0.95,0],[0.1,0.8,0.1]]

loss = tf.keras.losses.categorical_crossentropy(y_true,y_pred)
print(loss.numpy())

print(-np.log(0.95), -np.log(0.1))

[0.05129331 2.3025851 ]
0.05129329438755058 2.3025850929940455


In [5]:
import tensorflow as tf
import numpy as np

a=np.array([[0.3,2.9,4.0]])
sm=tf.keras.activations.softmax(tf.convert_to_tensor(a))
print(sm.numpy())

[[0.01821127 0.24519181 0.73659691]]
